name: My first workflow

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
        - name: Action
          uses: actions/checkout@v6
           
        - name: List and read files
          run: |
           echo "my first project"
           ls -ltra
           cat README.md

        - name: ASCII Art work
          run: cowsay -f dragon "hai mone hmm" >> dragon.txt

        # - name: list the files
        #   run: ls

        # - name: read the file
        #   run: cat README.md