name: Build Test Deploy Demo
env: 
  variable: password
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: environment variable
        run: |
          echo "environment variable is" $variable
          echo "another format is" ${{env.variable}}

      - name: Build step
        run: |
          mkdir build
          echo "Build completed successfully" > build/output.txt
      - name: environment variable
        run: |
          echo "environment variable is" $variable
          echo "another format is" ${{env.variable}}

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-files
          path: build/

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: build-files

      - name: Test step
        run: |
          cat output.txt
          echo "Tests passed successfully"

  deploy:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: build-files

      - name: Deploy step
        run: |
          cat output.txt
          echo "Deploying application..."
