name: Learning workflow #providing name to a new workflow

on: 
   push #when will be the github action executed
  
jobs: 
  demo:
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      -name: demo
       run: |
         echo "new demo"