name: Build Test Deploy Demoss
# env: 
#   variable: password
on:
  workflow_dispatch:
  push:
  # #push:commit
  #   branches:
  #     - main

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{matrix.os}}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: environment variable
        run: |
          echo "another format is" ${{secrets.variable}}

      - name: Build step
        run: |
          mkdir build
          echo "Build completed successfully" > build/output.txt
      - name: environment variable
        run: |
          echo "environment variable is" $variable
          echo "another format is" ${{env.variable}}
