name: Learning workflow #providing name to a new workflow

on: 
   push #when will be the github action executed
  
jobs: 
  demo:
    steps:
      -name: demo
       run: |
         mkdir: hello
         echo "new demo" > hello/output.txt