name: build test deploy     #workflow name

on: push                   #github actions

jobs:
  name: build
  runs-on: ubuntu-linux
  
  steps:
    - name: checkout
      uses: actions/checkout@v4

    - name: environment
      env: 
        password: demo

    - name: build code 
      run: |
       mkdir: file
       echo "demo code"

    - name: build artifact
      uses: actions/upload-artifact@v4
      with:
        name: build-artifact
        path: file/

