name: build test deploy jobs

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    
    
    steps: 
      - name: checkout
        uses: actions/checkout@v4
      
      - name: build step
        run: |
          mkdir build
          echo "build completed successfully" > build/output.text

      - name: artifact upload
        uses: actions/upload-artifact@v4
        with: 
          name: build files
          path: build/
  
  test:
    runs-on: ubuntu-latest

    steps: 
      - name: testing step
        run: |
          echo "test completed success"

  deploy:
    runs-on: ubuntu-latest

    steps: 
      - name: deploy step
        run: |
          echo "deploy completed"