name: Learning workflow #providing name to a new workflow

on: 
   push: #when will be the github action executed da
  
jobs: 
  demo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: demo
        run: |
         echo "new demo"

      - name: ls 
        run: ls -ldr

      - name: read files
        run: cat README.md
       